name: "kokoro-model"
platform: "onnxruntime_onnx"
max_batch_size: 0

input [
  {
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [ 1, -1 ]
  },
  {
    name: "style"
    data_type: TYPE_FP32
    dims: [ 1, 256 ]
  },
  {
    name: "speed"
    data_type: TYPE_INT32
    dims: [ 1 ]
  }
]

output [
  {
    name: "waveform"
    data_type: TYPE_FP32
    dims: [ -1 ]
  },
  {
    name: "duration"
    data_type: TYPE_INT64
    dims: [ -1 ]
  }
]

instance_group [
  {
    count: 4
    kind: KIND_GPU
    gpus: [ 0 ]
  }
]

default_model_filename: "model.onnx"